services:
  #################
  ## Application ##
  #################
  geolocation:
    image: 'geolocation:0.1.0'
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: geolocation
      DB_PASSWORD: geolocation
      DB_DATABASE: geolocation
      ## For logging to stdout instead of to a collector
      #OTEL_TRACES_EXPORTER: console
      #OTEL_METRICS_EXPORTER: console
      #OTEL_LOGS_EXPORTER: console
      #OTEL_TRACES_EXPORTER: otlp
      #OTEL_METRICS_EXPORTER: otlp
      #OTEL_LOGS_EXPORTER: otlp
      OTEL_SERVICE_NAME: geolocation
      OTEL_METRIC_EXPORT_INTERVAL: 15000
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    #logging:
    #  driver: loki
    #  options:
    #    loki-url: "http://localhost:3100/loki/api/v1/push"
    networks:
      - geolocation-network

  #################
  ## Database ##
  #################
  postgres:
    image: postgis/postgis:16-master
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: geolocation
      POSTGRES_PASSWORD: geolocation
      POSTGRES_DB: geolocation
    networks:
      - geolocation-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_URI: "postgres:5432/geolocation?sslmode=disable"
      DATA_SOURCE_USER: "geolocation"
      DATA_SOURCE_PASS: "geolocation"
    networks:
      - geolocation-network
    depends_on:
      - postgres

  ###################
  ## Observability ##
  ###################
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.121.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - "./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml"
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    depends_on:
      - jaeger
      - prometheus
    networks:
      - geolocation-network

  jaeger:
    image: jaegertracing/all-in-one:1.67.0
    volumes:
      - "./observability/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "14250:14250"
      - "16685:16685" # GRPC
      - "16686:16686" # UI
    networks:
      - geolocation-network

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - geolocation-network

  #promtail:
  #  image: grafana/promtail:2.9.10
  #  volumes:
  #    - /var/log:/var/log
  #  command: -config.file=/etc/promtail/config.yml
  #  networks:
  #    - geolocation-network

  loki:
    image: grafana/loki:3.4.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - geolocation-network

  grafana:
    image: grafana/grafana:11.5.2
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./observability/dashboards:/etc/grafana/provisioning/dashboards/
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: true
        - name: Jaeger
          type: jaeger
          url: http://jaeger:16686
          access: proxy
          # UID should match the datasourceUid in derivedFields.
          #uid: my_jaeger_uid
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          jsonData:
            httpMethod: POST
            manageAlerts: true
            prometheusType: Prometheus
            prometheusVersion: 2.44.0
            cacheLevel: 'High'
            disableRecordingRules: false
            incrementalQueryOverlapWindow: 10m
        - name: Geolocation Postgres
          type: postgres
          url: postgres:5432
          user: scala
          secureJsonData:
            password: 'geolocation'
          jsonData:
            database: geolocation
            sslmode: 'disable' # disable/require/verify-ca/verify-full
            maxOpenConns: 100 # Grafana v5.4+
            maxIdleConns: 100 # Grafana v5.4+
            maxIdleConnsAuto: true # Grafana v9.5.1+
            connMaxLifetime: 14400 # Grafana v5.4+
            postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
            timescaledb: false
        EOF
        /run.sh
    networks:
      - geolocation-network

networks:
  geolocation-network:
    driver: bridge
