apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: geolocation
  labels:
    app: otel-collector
    component: otel-collector-config
data:
  otel-collector-config.yaml: |-
    {{- tpl ($.Files.Get "otel-collector-config.yaml") . | nindent 4 }}
