apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: {{ .Values.appName }}-prometheus-metrics-port
    protocol: TCP
    port: 8888
    nodePort: 30888
  - name: {{ .Values.appName }}-prometheus-exporter-port
    protocol: TCP
    port: 8889
    nodePort: 30889
  - name: {{ .Values.appName }}-otlp-grpc-receiver-port
    protocol: TCP
    port: 4317
    nodePort: 30317
  - name: {{ .Values.appName }}-otlp-http-receiver-port
    protocol: TCP
    port: 4318
    nodePort: 30318
