apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation
  namespace: geolocation
  labels:
    app: geolocation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation
  template:
    metadata:
      labels:
        app: geolocation
    spec:
      containers:
      - name: geolocation
        image: geolocation:0.1.0
        env:
          - name: DB_HOST
            value: "postgres"
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            value: "geolocation"
          - name: DB_PASSWORD
            value: "geolocation"
          - name: DB_DATABASE
            value: "geolocation"
          - name: OTEL_SERVICE_NAME
            value: "geolocation"
          - name: OTEL_METRIC_EXPORT_INTERVAL
            value: "15000"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: geolocation
  namespace: geolocation
spec:
  type: NodePort
  selector:
    app: geolocation
  ports:
  - name: geolocation-port
    protocol: TCP
    port: 8080
    nodePort: 30080
