apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: geolocation
  labels:
    app: jaeger
    component: jaeger-config
data:
  jaeger.yml: |
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: geolocation
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.4.0
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: METRICS_STORAGE_TYPE
              value: "prometheus"
            - name: PROMETHEUS_SERVER_URL
              value: "http://prometheus:9090"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: geolocation
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
  - name: jaeger-ui-port
    protocol: TCP
    port: 16686
    nodePort: 30086
  - name: jaeger-grpc-port
    protocol: TCP
    port: 4317
    nodePort: 30250
  - name: jaeger-http-port
    protocol: TCP
    port: 4318
    nodePort: 30085
  - name: jaeger-http-sampling-port
    protocol: TCP
    port: 5778
    nodePort: 30778
  - name: jaeger-span-port
    protocol: TCP
    port: 9411
    nodePort: 30411
