apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: geolocation
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.4.2
          args:
            - "-config.file=/etc/loki/local-config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: geolocation
spec:
  type: NodePort
  selector:
    app: loki
  ports:
  - name: loki-port
    protocol: TCP
    port: 3100
    nodePort: 30100
