apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: geolocation
  labels:
    app: otel-collector
    component: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      otlp:
        endpoint: jaeger:4317
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
        send_timestamps: true
      otlphttp/loki:
        endpoint: "http://loki:3100/otlp"
        tls:
          insecure: true

    processors:
      batch:
        timeout: 10s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/loki]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: geolocation
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.121.0
          args:
            - "--config=/etc/otel-collector-config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: geolocation
spec:
  type: NodePort
  selector:
    app: otel-collector
  ports:
  - name: otel-collector-prometheus-metrics-port
    protocol: TCP
    port: 8888
    nodePort: 30888
  - name: otel-collector-prometheus-exporter-port
    protocol: TCP
    port: 8889
    nodePort: 30889
  - name: otel-collector-otlp-grpc-receiver-port
    protocol: TCP
    port: 4317
    nodePort: 30317
  - name: otel-collector-otlp-http-receiver-port
    protocol: TCP
    port: 4318
    nodePort: 30318
