kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-pv-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  storageClassName: kind-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
