kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"

