apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: {{ .Values.appName }}
    protocol: TCP
    port: {{ .Values.port }}
    nodePort: 32543
  type: NodePort 
  selector:
    app: {{ .Values.appName }}
