kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kind-hostpath
  namespace: {{ .Values.namespace }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path

