object Versions {
  val catsCore                = "2.12.0"
  val catsEffect              = "3.5.4"
  val caseInsensitive         = "1.4.0"
  val circe                   = "0.14.10"
  val ciris                   = "3.6.0"
  val flyway                  = "10.19.0"
  val fs2                     = "3.11.0"
  val gatling                 = "3.13.1"
  val http4s                  = "0.23.27"
  val http4sPrometheusMetrics = "0.25.0"
  val ip4s                    = "3.6.0"
  val jsoniterScalaMacro      = "2.30.15"
  val log4cats                = "2.7.0"
  val logback                 = "1.4.14"
  val logstashLogbackEncoder  = "8.0"
  val munit                   = "1.0.1"
  val munitCatsEffect         = "2.0.0"
  val otel4s                  = "0.8.0"
  val opentelemetry           = "1.38.0"
  val postgres                = "42.7.4"
  val prometheus              = "1.3.2"
  val skunk                   = "1.0.0-M7"
  val slf4j                   = "2.0.16"
  val tapir                   = "1.11.9"
  val testContainers          = "0.41.4"
  val weaver                  = "0.8.3"
}
