apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: geolocation
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.5.2
        env:
          - name: GF_PATHS_PROVISIONING
            value: "/etc/grafana/provisioning"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: "Admin"
        command:
          - sh
          - -euc
          - |
            mkdir -p /etc/grafana/provisioning/datasources
            cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              access: proxy
              orgId: 1
              url: http://loki:3100
              basicAuth: false
              isDefault: true
              version: 1
              editable: true
            - name: Jaeger
              type: jaeger
              url: http://jaeger:16686
              access: proxy
              # UID should match the datasourceUid in derivedFields.
              #uid: my_jaeger_uid
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus:9090
              jsonData:
                httpMethod: POST
                manageAlerts: true
                prometheusType: Prometheus
                prometheusVersion: 2.44.0
                cacheLevel: 'High'
                disableRecordingRules: false
                incrementalQueryOverlapWindow: 10m
            - name: Geolocation Postgres
              type: postgres
              url: postgres:5432
              user: geolocation
              secureJsonData:
                password: 'geolocation'
              jsonData:
                database: geolocation
                sslmode: 'disable' # disable/require/verify-ca/verify-full
                maxOpenConns: 100 # Grafana v5.4+
                maxIdleConns: 100 # Grafana v5.4+
                maxIdleConnsAuto: true # Grafana v9.5.1+
                connMaxLifetime: 14400 # Grafana v5.4+
                postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
                timescaledb: false
            EOF
            /run.sh
