apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: geolocation
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: grafana-port
    protocol: TCP
    port: 3000
    nodePort: 30000
