apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}-shard
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: {{ .Values.appName }}-shard
        app.kubernetes.io/version: 2.15.0
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Values.appName }}
        args:
        - --resources=pods
        - --node=$(NODE_NAME)
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      serviceAccountName: {{ .Values.appName }}
