apiVersion: v1
kind: Service
metadata:
  name: geolocation
  namespace: geolocation
spec:
  type: NodePort
  selector:
    app: geolocation
  ports:
  - name: geolocation-port
    protocol: TCP
    port: 8080
    nodePort: 30080
