apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: geolocation
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
  - name: jaeger-ui-port
    protocol: TCP
    port: 16686
    nodePort: 30086
  - name: jaeger-grpc-port
    protocol: TCP
    port: 4317
    nodePort: 30250
  - name: jaeger-http-port
    protocol: TCP
    port: 4318
    nodePort: 30085
  - name: jaeger-http-sampling-port
    protocol: TCP
    port: 5778
    nodePort: 30778
  - name: jaeger-span-port
    protocol: TCP
    port: 9411
    nodePort: 30411
